### ISSUE TITLE
NonAdminBackup status should clearly mention that the associated velero backup has been removed

### ISSUE THREAD

**Issue by PrasadJoshi12** [migtools/oadp-non-admin#195]
When velero backup is deleted/expired and removed by velero controller, The associated nonAdminBackup should indicate that clearly for nonAdmin user. Currently it shows the backup is getting delete but in reality backup can be gone since long time.

Steps to follow:-

1. Create  a non admin backup with smaller ttl or remove backup after it gets completed
```console
$ cat nab.yaml 
apiVersion: oadp.openshift.io/v1alpha1
kind: NonAdminBackup
metadata:
  name: test-nab
spec:
  backupSpec:
    includedNamespaces:
    - "test-nac"
    ttl: 0h01m0s
```

The CR shows the velero backup status as deleting. 

```yaml
veleroBackup:
    nacuuid: test-nac-test-nab1-a7b201d5-7663-4ab3-a654-eeca67aebfcc
    name: test-nac-test-nab1-a7b201d5-7663-4ab3-a654-eeca67aebfcc
    namespace: openshift-adp
    status:
      completionTimestamp: "2025-02-17T12:17:14Z"
      expiration: "2025-02-17T12:18:10Z"
      formatVersion: 1.1.0
      hookStatus: {}
      phase: Deleting
      progress:
        itemsBackedUp: 21
        totalItems: 21
      startTimestamp: "2025-02-17T12:17:10Z"
      version: 1
```
