### ISSUE TITLE
WATCH_NAMESPACE var is misleading.

### ISSUE THREAD

**Issue by kaovilai** [migtools/oadp-non-admin#215]
Being used as OADP NS discovery.

It is not even needed for OADP to pass this value if you have this env on nac deployment

```yaml
    env:
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
```
