### ISSUE TITLE
Reconcile loop is not exitting properly

### ISSUE THREAD

**Issue by mpryc** [migtools/oadp-non-admin#65]
Changed introduced after `94c4be9bf93da2d791281d2aaca54655d28213161` caused reconcile loop to not exit properly and when the state is incorrect e.g. `BackingOff` re-enter reconcile.

**Comment by mateusoliveira43** [comment]
did not found this commit, can you link it?

**Comment by mpryc** [comment]
The last correctly working was:

`fix: Add more documenation to project (#16)` One of later commits caused the behavior.

To reproduce:

Create NonAdminBackup without proper spec, e.g. Then reconcile loop will enter every few sec.

```
apiVersion: nac.oadp.openshift.io/v1alpha1
kind: NonAdminBackup
metadata:
  name: example
  namespace: nacproject
spec: {}
```
